### ISSUE TITLE
Location Manager

### ISSUE THREAD

**Issue by BrokenKage** [peacefulcraft-network/SwordCraftOnline#114]
Might need a consistent list of locations stored in .yml loaded onto server or in static hashmap. Storing prominent location names to be checked against in quests, world guard, etc. 

This would help in avoiding String based errors in determining city names. For the current Quest skeleton I need to be able to check against these locations to validate proper quest loading.

**Comment by Parsonswy** [comment]
@BrokenKage 
It might be easier to just establish a convention and make a Location class that would wrap Bukkit's Location and let us add a name property. We can look into making the class serializable so that we can do things like `YAMLConfiguration.set('foo', Location);` to write to config files. 
```YAML
[what the point is]:
    name: "QuestEnd"
    x: 354
    y: 112
    z: 231
```
I think to load in from config we'd need to read in the name and cords as 4 sperate bits (`YAMLConfiguration.getString()`, `.getInt()` x3), and then instantiate the Location class.

I don't know that making a central list of all locations would be all that useful. Is there ever a case where we'd need to access a location outside of the context of that location? IE; need to TP to a quest point without knowing that name of the quest.

[This Spigot thread](https://www.spigotmc.org/threads/tutorial-bukkit-custom-serialization.148781/) kind of explains how to make classes serializable.

**Comment by BrokenKage** [comment]
@Parsonswy 
I can make a continuation of the class pretty easily. The issue I was looking into was needing borders similar to World Guard around a specific location or interface with World Guard to receive info when players cross into a location. 

Could be useful in the context of an "Escort Quest" which is bringing an npc from one location to another. It would be easier on the player to detect them entering a city limits as opposed to a single block in the city.
